import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join } from 'node:path';
const ROOT='/home/user/260725/baby-care-3d';
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};
const {port}=await new Promise(r=>{const s=createServer(async(q,p)=>{try{let u=decodeURIComponent(q.url.split('?')[0]);if(u.endsWith('/'))u+='index.html';const f=join(ROOT,u);const b=await readFile(f);p.writeHead(200,{'Content-Type':MIME[extname(f)]||'application/octet-stream'});p.end(b);}catch{p.writeHead(404).end('404');}});s.listen(0,'127.0.0.1',()=>r({port:s.address().port}));});
const br=await chromium.launch({args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await br.newPage({viewport:{width:1440,height:900}});
page.on('pageerror',e=>console.log('PAGEERROR',e.message));
page.on('console',m=>console.log('CONSOLE',m.type(),m.text()));
await page.goto(`http://127.0.0.1:${port}/.uitest.html`);
await page.waitForFunction(()=>!!window.__UI__);
await page.evaluate(()=>{window.__UI__.startGame();window.__UI__.meter('food',.14);});
await page.waitForTimeout(1200);
console.log(await page.evaluate(()=>({time: window.__UI__._time, needAcc: window.__UI__._needAcc, acts: Object.keys(window.__UI__.els.acts), lowClass: document.querySelector('.meter[data-meter=food]').className})));
await br.close();process.exit(0);
